config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope format: false do
    # Github login
    devise_for :users, path: '/', controllers: {
      omniauth_callbacks: 'sessions'
    }

    # Sign in, Sign up & Profile
    devise_scope :user do
      get '@:login', to: 'users#show', as: 'profile'
      delete '@:login', to: 'users#destroy'

      get 'login', to: redirect('/auth/github'), as: 'login'
      get 'logout', to: 'sessions#logout', as: 'logout'
    end

    # Pages
    root 'pages#index'
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
# frozen_string_literal: true

class Course < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :repo_id, presence: true, uniqueness: true
  validates :repo_name, presence: true, uniqueness: {
    scope: :user_id, case_sensitive: false
  }
  validates :repo_url, presence: true

  def to_param
    repo_name
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :omniauthable, omniauth_providers: [:github]
  has_many :courses, dependent: :destroy

  # Required fields
  validates :login, presence: true, uniqueness: { case_sensitive: false }
  validates :avatar_url, presence: true
  validates :github_id, presence: true, uniqueness: true
  validates :github_token, presence: true
  validates :github_url, presence: true

  def self.find_or_create_by(payload)
    attrs = AuthHash.new(payload).user_info

    # Let's see if we can find an existing user
    user = User.find_by_github_id(attrs[:github_id])

    # Either we have a new user
    if user.nil?
      user = User.create!(attrs)

    # Or we should update our existing user's attributes
    else
      # TODO: Don't update if access token has lower scopes
      user.update_attributes(attrs)
    end

    user
  end

  def token
    github_token
  end

  def to_param
    # We use `login` as an identifier in `user#show` and `user#destroy` routes
    login
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(_res)
    request.env['omniauth.origin'] || root_url
  end

  def after_sign_out_path_for(_res)
    root_url
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < Devise::OmniauthCallbacksController
  def github
    @user = User.find_or_create_by(payload)
    sign_in_and_redirect @user
  end

  def logout
    @user = current_user
    sign_out_and_redirect @user
  end

  private

  def payload
    request.env['omniauth.auth']
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show destroy]

  # GET /@login
  def show
  end

  # DELETE /@login
  def destroy
    @user.destroy
    redirect_to root_url, notice: 'User was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find_by!(login: params[:login])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tutorship</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'shared/header' %>

    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>It works</h1>

app/views/shared/_header.html.erb
<table>
  <tr>
    <td>
      <%= link_to root_path do %>
        Home
      <% end %>
    </td>

    <% if user_signed_in? %>
    <td>
      Welcome,
      <%= link_to profile_path(current_user) do %>
        <%= current_user.name %>
      <% end %>
    </td>

    <td>
      <%= link_to logout_path do %>
        Sign out
      <% end %>
    </td>
    <% else %>
    <td>
      <%= link_to login_path, data: { turbolinks: false } do %>
        Sign in
      <% end %>
    </td>
    <% end %>
  </tr>
</table>

<br>

app/views/users/show.html.erb
<img src="<%= @user.avatar_url %>" />
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Login:</strong>
  <%= @user.login %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Location:</strong>
  <%= @user.location %>
</p>

<p>
  <strong>GitHub URL:</strong>
  <%= @user.github_url %>
</p>

<%= link_to 'Back', users_path %>